[package]
name = "cloudflare-ddns"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[profile.release]
    opt-level = 3
    lto = "fat"
    strip = true

[dependencies.windows]
version = "0.51.1"
features = [
    "Win32_UI_WindowsAndMessaging",
    "Win32_Foundation"
]

[dependencies]
tokio        = { version = "1.32.0", features = ["full"] }
futures      = { version = "0.3.28"  }
reqwest      = { version = "0.11.19", features = ["stream"] }
mimalloc     = { version = "*", default-features = false }
uuid         = { version = "1.4.1", features = ["v4"] }
bytes        = "1.4.0"
serde        = "1.0.185"
async-trait  = "0.1.73"
simd-json    = "0.10.6"
