concurrent-resolve = 24

["https://checkip.amazonaws.com/"]
steps = ["Plaintext"]

["https://api.ipify.org/"]
steps = ["Plaintext"]

["https://ipv4.icanhazip.com/"]
steps = ["Plaintext"]

["https://4.ident.me/"]
steps = ["Plaintext"]

["https://v4.tnedi.me/"]
steps = ["Plaintext"]

["https://v4.ipv6-test.com/api/myip.php"]
steps = ["Plaintext"]

["https://myip.dnsomatic.com/"]
steps = ["Plaintext"]

["https://ipinfo.io/ip"]
steps = ["Plaintext"]

["https://ipv4.nsupdate.info/myip"]
steps = ["Plaintext"]

["https://dynamic.zoneedit.com/checkip.html"]
steps = ["Plaintext"]

["https://api.ipify.org/?format=json"]
steps = [{ Json = { key = "ip" } }]