[build]
target = "x86_64-unknown-linux-musl"
rustflags = [
    "-C", "target-cpu=native",
    "-C", "target-feature=+crt-static",
    "-Z", "location-detail=none",
]

[unstable]
build-std = ["std", "panic_abort", "core", "alloc"]
build-std-features = ["panic_immediate_abort"]
